# Generated by Django 5.1 on 2024-08-19 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("f114169b-47ac-48e6-97a1-b3d3083f698f"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60, null=True)),
                ("surname", models.CharField(max_length=60, null=True)),
                ("birth_date", models.DateField(null=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("1-2", "1-2 times a week"),
                            ("2-4", "2-4 times a week"),
                            ("5-7", "5-7 times a week"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("89dcdfd1-36df-49c8-b49d-7cb929ad7a86"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "calories",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "proteins",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "carbohydrates",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "fats",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "fiber",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
