# Generated by Django 5.1 on 2024-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="activity",
            field=models.CharField(
                choices=[
                    ("1-2 times a week", "1-2 times a week"),
                    ("2-4 times a week", "2-4 times a week"),
                    ("5-7 times a week", "5-7 times a week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal",
            field=models.CharField(
                choices=[
                    ("Lose weight", "Lose weight"),
                    ("Maintain weight", "Maintain weight"),
                    ("Gain weight", "Gain weight"),
                ],
                default="Maintain",
                null=True,
            ),
        ),
    ]
