# Generated by Django 5.1 on 2024-08-18 15:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activity",
            field=models.CharField(
                choices=[
                    ("1-2", "1-2 times a week"),
                    ("2-4", "2-4 times a week"),
                    ("5-7", "5-7 times a week"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("24d15f73-0e01-49c7-a233-f1ff645c328f"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("892d00f6-08e8-49e4-80bd-b265041ae24c"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
