# Generated by Django 5.1 on 2024-08-18 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="surname",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a734a176-31a8-4876-a159-ebbf56e06104"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4d4b7105-059a-47d0-a921-6f0770bd041e"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
