# Generated by Django 5.1 on 2024-08-22 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "calories_per_100g",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("proteins", models.DecimalField(decimal_places=2, max_digits=5)),
                ("carbohydrates", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fats", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fiber", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_keto_friendly", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_lactose_free", models.BooleanField(default=False)),
                ("is_nut_free", models.BooleanField(default=False)),
                ("is_soy_free", models.BooleanField(default=False)),
                ("is_shellfish_free", models.BooleanField(default=False)),
                ("is_high_protein", models.BooleanField(default=False)),
                ("is_low_sugar", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=70,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("description", models.TextField()),
                ("preparation_time", models.DurationField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(related_name="dishes", to="food.product"),
                ),
            ],
        ),
    ]
