# Generated by Django 5.1 on 2024-08-24 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_dish_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="product_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png"]
                    )
                ],
            ),
        ),
    ]
