# Generated by Django 5.1 on 2024-08-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_remove_product_quantity_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="carbohydrates",
            new_name="carbohydrates_per_100_g",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="fats",
            new_name="fats_per_100_g",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="fiber",
            new_name="fiber_per_100_g",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="proteins",
            new_name="proteins_per_100_g",
        ),
    ]
