# Generated by Django 5.1 on 2024-08-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_rename_carbohydrates_product_carbohydrates_per_100_g_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="calories_per_100g",
            new_name="calories_per_100_g",
        ),
    ]
