# Generated by Django 5.1 on 2024-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_rename_calories_per_100g_product_calories_per_100_g"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="sugar_per_100_g",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name="dish",
            name="products",
            field=models.ManyToManyField(
                null=True, related_name="dishes", to="food.product"
            ),
        ),
    ]
